### ISSUE TITLE
The mod was originally licensed under GPLv3

### ISSUE THREAD

**Issue by taikedz** [DI3HARD139/dcb-everamzah-#1]
The mod was originally licensed under the GPLv3 by everamzah at [commit d4751be](https://github.com/taikedz/everamzah-dcb/blob/master/LICENSE)

It cannot be relicensed under MIT without the express authorization from the original author.

Even in his absence, we cannot re-license it.

**Comment by DI3HARD139** [comment]
I didn't have a copy of the original liscense. Thanks for sharing this! Licence has been corrected!
